Repository prgrms-web-devcourse/Team_Ahpuh_Surf_FE, pull requests merged in 2021-12, with the labels that each got.

#28 Config: absolute path 설정 및 자잘한 오류 수정
  .eslintrc
  .storybook/main.js
  hooks/base/useForm.js
  hooks/base/useHover.js
  jsconfig.json
  package-lock.json
  package.json
  stories/useHover.stories.js
Labels: Fix, Config

#17 Feat: useForm 훅 구현
  hooks/base/useForm.js
Labels: Feat

#24 Fix: hooks 폴더 정리
  hooks/useForm.js
  hooks/useHover.js
  stories/Button.jsx
  stories/Button.stories.jsx
  stories/button.css
  stories/useHover.stories.jsx
Labels: Fix

#30 🔧 Config: 절대경로 구현 및 자잘한 오류 수정
  .eslintrc
  .storybook/main.js
  hooks/base/useForm.js
  hooks/base/useHover.js
  jsconfig.json
  package-lock.json
  package.json
  stories/useHover.stories.js
Labels: Config

#31 Fix: hooks 폴더 구조 정리
  hooks/useForm.js
  hooks/useHover.js
  stories/Button.jsx
  stories/Button.stories.jsx
  stories/button.css
  stories/useHover.stories.jsx
Labels: Fix

#21 Feat: useForm storybook 구현
  stories/hooks/useForm.stories.js
Labels: Feat

#36 Dep: react-icons 추가
  package-lock.json
  package.json
  yarn.lock
Labels: Dep

#43 Refactor: proptypes, defaultProps 추가
  components/base/Avatar/index.jsx
  pages/_app.jsx
Labels: Refactor

#44 Feat: Header 컴포넌트 구현
  assets/logo/logo_italic_fill.svg
  assets/logo/logo_normal_fill.svg
  components/base/Avatar/index.jsx
  components/common/Header/index.jsx
  pages/_app.jsx
  stories/common/Header.stories.jsx
Labels: Feat

#46 Style: 프로젝트 전반 절대경로 적용
  assets/logo/index.js
  components/base/Logo/index.jsx
  components/common/Header/index.jsx
  components/common/index.js
  pages/index.jsx
  stories/base/Badge.stories.jsx
  stories/base/Logo.stories.jsx
  stories/common/Header.stories.jsx
  stories/hooks/useForm.stories.jsx
  stories/hooks/useHover.stories.jsx
Labels: Style

#50 Assets: 폰트 추가
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoB.ttf
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoEB.ttf
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoH.ttf
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoL.ttf
  public/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.ttf
  public/fonts/Frutiger/Frutiger.woff
  public/fonts/Frutiger/Frutiger_bold.woff
Labels: Assets

#52 Fix: reset.js → globals.css
  pages/_app.jsx
  styles/globals.css
  styles/reset.js
Labels: Fix

#53 UI: font-face 추가
  styles/globals.css
Labels: UI

#54 Feat: Toggle 컴포넌트 구현
  components/base/Toggle/index.jsx
  components/base/index.js
  stories/base/Toggle.stories.jsx
Labels: Feat

#57 Feat: Upload 컴포넌트 구현
  README.md
  components/base/Upload/index.jsx
  components/base/index.js
  components/common/Header/index.jsx
  public/images/sample.jpeg
  public/images/upload.svg
  stories/base/Upload.stories.jsx
Labels: Feat

#61 Feat: Navbar 구현
  .eslintrc
  components/common/Navbar/index.jsx
  components/common/index.js
  pages/_app.jsx
  stories/common/Navbar.stories.jsx
Labels: Feat

#64 Feat: Dropdown 컴포넌트 구현
  .eslintrc
  components/base/Dropdown/index.jsx
  components/base/Dropdown/style.js
  constants/DropdownData.js
  styles/globals.css
  styles/theme.js
Labels: Feat

#72 Feat:CategoryCard 컴포넌트 구현
  .eslintrc
  components/domain/CategoryCard/index.jsx
  components/domain/index.js
  stories/domain/CategoryCard.stories.js
Labels: Feat

#75 Feat:PostDetail 컴포넌트 구현
  components/base/index.js
  components/domain/PostDetail/index.jsx
  components/domain/PostDetail/style.js
  components/domain/index.js
  stories/domain/PostDetail.stories.jsx
Labels: Feat

#86 Feat: DatePicker 구현
  .storybook/main.js
  components/domain/Calendar/index.jsx
  components/domain/Calendar/style.js
  components/domain/DatePicker/index.jsx
  components/domain/index.js
  package.json
  stories/domain/Calendar.stories.jsx
  stories/domain/DatePicker.stories.jsx
  yarn.lock
Labels: Feat

#83 Feat: Modal 컴포넌트 구현
  components/base/Modal/index.jsx
  components/base/Modal/style.js
  components/base/index.js
Labels: Feat

#73 Fix: logo 이미지 경로 수정
  components/base/Logo/index.jsx
  public/images/logo/index.js
  public/images/logo/logo_italic.svg
  public/images/logo/logo_italic_fill.svg
  public/images/logo/logo_normal.svg
  public/images/logo/logo_normal_fill.svg
Labels: Fix

#78 Feat:DashboardCard 컴포넌트 구현
  components/domain/DashboardCard/index.jsx
  components/domain/DashboardCard/style.js
  components/domain/index.js
  stories/domain/DashboardCard.stories.jsx
Labels: Feat

#79 Feat:NoticeCard 컴포넌트 구현
  components/domain/NoticeCard/index.jsx
  components/domain/index.js
  stories/domain/NoticeCard.stories.jsx
Labels: Feat

#81 Refactor: like button 겹침 문제 해결
  components/domain/PostDetail/index.jsx
  components/domain/PostDetail/style.js
Labels: Refactor

#67 Fix: Navbar storybook control 설정
  stories/common/Navbar.stories.jsx
Labels: Fix

#87 Feat: Tabs 컴포넌트 1차 구현
  components/domain/Tabs/TabItem/index.jsx
  components/domain/Tabs/TabPanel/index.jsx
  components/domain/Tabs/index.jsx
  components/domain/index.js
  stories/domain/Tabs.stories.jsx
Labels: Feat

#90 Refactor: DatePicker에서 Calendar 컴포넌트 랜더링 위치 수정, style파일 추가
  components/base/index.js
  components/domain/Calendar/index.jsx
  components/domain/Calendar/style.js
  components/domain/DatePicker/index.jsx
  components/domain/DatePicker/style.js
  stories/domain/DatePicker.stories.jsx
Labels: Fix, Refactor

#85 Feat: Textarea 컴포넌트 구현
  components/base/Textarea/index.jsx
  components/base/index.js
  stories/base/Textarea.stories.jsx
  styles/theme.js
Labels: Feat

#94 UI: Storybook에 theme 적용
  .storybook/preview.js
Labels: UI

#92 Feat, Fix, UI: Tabs 컴포넌트에 Modal 적용
  components/base/Modal/index.jsx
  components/base/Modal/style.js
  components/base/index.js
  components/domain/Tabs/TabPanel/index.jsx
  components/domain/Tabs/index.jsx
Labels: Fix, Feat, UI

#107 UI: Category Manage Page 구현
  SampleData/CategoryManage.js
  components/domain/CategoryCard/index.jsx
  pages/CategoryManage.jsx
Labels: UI

#109 Feat, Dep: MUI, toastify 설치, ScoreSlider 구현
  components/domain/ScoreSlider/index.jsx
  components/domain/ScoreSlider/style.js
  components/domain/index.js
  next.config.js
  package.json
  stories/domain/ScoreSlider.stories.jsx
  yarn.lock
Labels: Feat, Dep

#96 Fix: DatePicker 전달 클릭 오류 수정
  components/base/index.js
  components/domain/Calendar/index.jsx
Labels: Fix

#111 Feat: Loading 컴포넌트 구현
  components/base/Loading/index.jsx
  components/base/index.js
  package.json
  public/images/loadingAnimation.json
  stories/base/Loading.stories.jsx
  yarn.lock
Labels: Feat

#117 Feat: RadialBar 컴포넌트 구현
  SampleData/RadialChartComponent.js
  components/domain/AreaChartComponent/README.md
  components/domain/RadialBarChartComponent/README.md
  components/domain/RadialBarChartComponent/getFilteredData.js
  components/domain/RadialBarChartComponent/index.jsx
  stories/domain/RadialChartComponent.stories.jsx
Labels: Feat

#116 UI: 404 페이지 마크업
  pages/404/index.jsx
  pages/404/style.js
  public/lottie/surfing-poodle.json
Labels: UI

#120 Refactor: Post 컴포넌트 style 수정
  components/domain/Post/index.jsx
  components/domain/Post/style.js
  package.json
Labels: Refactor

#121 UI: 메인 페이지 마크업
  components/base/Dropdown/index.jsx
  components/common/Header/index.jsx
  components/common/Navbar/index.jsx
  constants/PostData.js
  pages/main.jsx
  styles/globals.css
Labels: UI

#123 UI: 공통 레이아웃 스타일 수정
  pages/_app.jsx
Labels: UI

#124 UI: post/new 페이지 UI 구현
  components/base/Dropdown/index.jsx
  components/base/Dropdown/style.js
  components/base/Textarea/index.jsx
  components/base/Upload/index.jsx
  components/domain/Calendar/style.js
  components/domain/DatePicker/index.jsx
  components/domain/DatePicker/style.js
  components/domain/ScoreSlider/index.jsx
  components/domain/ScoreSlider/style.js
  pages/post/new/index.jsx
  pages/post/new/style.js
  stories/base/Upload.stories.jsx
  stories/domain/DatePicker.stories.jsx
  styles/theme.js
Labels: Refactor, UI

#128 UI: Signup, Login 컴포넌트 UI 구현
  components/base/Input/index.jsx
  hooks/useForm.js
  pages/login/index.jsx
  pages/signup/index.jsx
  pages/signup/style.js
  styles/globals.css
  styles/theme.js
  utils/SampleData/CategoryManage.js
  utils/SampleData/RadialChartComponent.js
  utils/SampleData/heatmapChart.js
  utils/validation/index.js
Labels: Refactor, UI, Assets, Style

#127 UI: MyPage 마크업
  SampleData/Mypage.js
  SampleData/heatmapChart.js
  components/domain/AreaChartComponent/getCurrentQuarter.js
  components/domain/AreaChartComponent/getDefaultOptions.js
  components/domain/AreaChartComponent/index.jsx
  components/domain/AreaChartComponent/sampleXNY1.js
  components/domain/AreaChartComponent/sampleXNY2.js
  components/domain/AreaChartComponent/style.js
  components/domain/AreaChartComponent/updateXAxis.js
  components/domain/Carot/index.jsx
  components/domain/ContentBox/index.jsx
  components/domain/EditAboutMe/index.jsx
  components/domain/EditAboutMe/style.js
  components/domain/HeatmapChartComponent/index.jsx
  components/domain/Profile/index.jsx
  components/domain/index.js
  pages/Mypage.jsx
  pages/index.jsx
  pages/myPageStyle.js
  stories/domain/AreaChartComponent.stories.jsx
  stories/domain/Carot.stories.jsx
  stories/domain/ContentBox.stories.jsx
  stories/domain/EditAboutMe.stories.jsx
Labels: Refactor, UI, Style

#130 Feat: axios interceptor, swr fetcher, api 함수 구현
  SampleData/RadialChartComponent.js
  constants/environment.js
  package.json
  pages/login/index.jsx
  utils/apis/category/index.js
  utils/apis/category/useGetTotalCategory.js
  utils/apis/fetcher.js
  utils/apis/interceptor.js
  utils/apis/post/deletePost.js
  utils/apis/post/index.js
  utils/apis/post/updatePost.js
  utils/apis/post/uploadPost.js
  utils/apis/post/useGetPost.js
  utils/apis/user/deleteUser.js
  utils/apis/user/index.js
  utils/apis/user/login.js
  utils/apis/user/updateUser.js
  utils/apis/user/useGetUser.js
  yarn.lock
Labels: Feat, Dep, Style

#136 Refactor: dummy data .. Util 하위 SampleData 폴더로 옮김, 컴포넌트 참조 경로 절대경로로 변경
  SampleData/RadialChartComponent.js
  components/domain/AreaChartComponent/README.md
  pages/main.jsx
  pages/mypage/edit/index.jsx
  pages/mypage/index.jsx
  stories/domain/AreaChartComponent.stories.jsx
  stories/domain/Carot.stories.jsx
  stories/domain/CategoryCard.stories.js
  stories/domain/ContentBox.stories.jsx
  stories/domain/DashboardCard.stories.jsx
  stories/domain/EditAboutMe.stories.jsx
  stories/domain/NoticeCard.stories.jsx
  stories/domain/Post.stories.jsx
  stories/domain/PostDetail.stories.jsx
  stories/domain/RadialChartComponent.stories.jsx
  stories/domain/ScoreSlider.stories.jsx
  utils/SampleData/AreaChartComponent1.js
  utils/SampleData/AreaChartComponent2.js
  utils/SampleData/CategoryCard.js
  utils/SampleData/Mypage.js
Labels: Refactor

#143 Feat: 월별 포스트 페이지 라우팅
  pages/posts/[month]/index.jsx
Labels: Feat

#144 :lipstick: UI: posts/month 마크업
  components/domain/Post/style.js
  pages/post/month/index.jsx
  utils/SampleData/Posts.js
Labels: UI

#146 Feat: AddSurModal 추가 in posts/new 페이지
  components/base/Dropdown/index.jsx
  components/base/Modal/index.jsx
  components/base/Textarea/index.jsx
  components/domain/AddSurfModal/index.jsx
  components/domain/AddSurfModal/style.js
  components/domain/DatePicker/index.jsx
  components/domain/ScoreSlider/index.jsx
  components/domain/index.js
  hooks/useToggle.js
  package.json
  pages/login/index.jsx
  pages/post/new/index.jsx
  pages/posts/new/index.jsx
  pages/posts/new/style.js
  pages/signup/index.jsx
  pages/signup/style.js
  yarn.lock
Labels: Feat, Dep

#151 Style: post detail page url 변경
  pages/posts/[month]/[postId]/index.jsx
Labels: Style

#154 Feat: CalendarCard 컴포넌트 구현
  components/domain/CalendarCard/calendar.jsx
  components/domain/CalendarCard/calendarStyle.js
  components/domain/CalendarCard/index.jsx
  components/domain/CalendarCard/style.js
Labels: Feat

#156 UI: 전체 카드 페이지 마크업
  components/base/Dropdown/index.jsx
  components/common/Navbar/index.jsx
  components/domain/AreaChartComponent/style.js
  components/domain/CalendarCard/style.js
  components/domain/Carot/index.jsx
  components/domain/index.js
  pages/_app.jsx
  pages/_document.jsx
  pages/index.jsx
  pages/posts/all/index.jsx
Labels: UI

#159 UI: 404 페이지 마크업 구현
  pages/404/index.jsx
  pages/404/style.js
Labels: UI

#152 UI: 둘러보기 페이지 마크업
  pages/explore/index.jsx
  utils/SampleData/Explores.js
Labels: UI

#163 UI: Signup 컴포넌트 scroll 제거
  pages/signup/style.js
Labels: UI

#165 FIx: Signup 컴포넌트트 userName -> username 변경
  pages/signup/index.jsx
Labels: Fix

#167 Fix: axios interceptor 구조 변경, 배포된 API 일부 반영
  constants/environment.js
  next.config.js
  pages/login/index.jsx
  pages/signup/index.jsx
  utils/apis/api.js
  utils/apis/category/deleteCategory.js
  utils/apis/category/index.js
  utils/apis/category/updateCategory.js
  utils/apis/category/uploadCategory.js
  utils/apis/category/useGetCategories.js
  utils/apis/category/useGetDashboard.js
  utils/apis/post/deletePost.js
  utils/apis/post/index.js
  utils/apis/post/updatePost.js
  utils/apis/post/uploadPost.js
  utils/apis/post/useGetPostsMonth.js
  utils/apis/user/deleteUser.js
  utils/apis/user/index.js
  utils/apis/user/login.js
  utils/apis/user/signup.js
  utils/apis/user/updateUser.js
Labels: Fix, Feat

#171 Fix: 토큰 확인 절차 추가
  utils/apis/api.js
Labels: Fix

#172 UI: 메인 페이지 마크업 구현
  components/domain/AreaChartComponent/index.jsx
  components/domain/AreaChartComponent/style.js
  components/domain/Post/style.js
  pages/_app.jsx
  pages/index.jsx
Labels: UI

#175 Fix: CORS 해결
  utils/apis/api.js
  utils/apis/fetcher.js
Labels: Fix

#177 Fix: withCredential: true in fetcher 함수
  utils/apis/fetcher.js
Labels: Fix

#182 Fix: toastify css 전역 설정
  components/domain/ScoreSlider/index.jsx
  pages/_app.jsx
Labels: Fix

#188 Feat: signup 페이지 API 적용
  constants/environment.js
  pages/signup/index.jsx
  utils/common/setTime.js
Labels: Feat

#187 Feat: 메인페이지 회원가입 toast 적용
  pages/index.jsx
Labels: Feat

#191 Fix: SWR custom hook url
  utils/apis/fetcher.js
Labels: Fix

#192 Feat: Login API 적용 및 쿠키확인 후 라우터
  pages/login/index.jsx
Labels: Feat

#194 Fix: 이름수정 useUser -> useGetUser
  utils/apis/user/useGetUser.js
Labels: Fix

#196 Fix: fetcher 토큰 Bearer 삭제
  utils/apis/fetcher.js
Labels: Fix

#198 Fix: header Authozation -> token
  utils/apis/fetcher.js
Labels: Fix

#200 Refactor: useGetCategories options 추가
  utils/apis/category/useGetCategories.js
Labels: Refactor

#202 Feat: changeToBlob 함수 구현
  utils/common/changeToBlob.js
Labels: Feat

#204 Feat: checkEmpty 함수 구현
  utils/validation/index.js
Labels: Feat

#206 Fix: interceptor header Authorization -> token 변경
  utils/apis/api.js
Labels: Fix

#213 Refactor: DatePicker delimiter 적용 in onChange
  components/domain/DatePicker/index.jsx
Labels: Refactor

#211 Feat: Dropdown 컴포넌트 isNew 추가
  components/base/Dropdown/index.jsx
Labels: Feat

#207 Wip: posts/new API 대기중
  components/base/Dropdown/index.jsx
  components/base/Textarea/index.jsx
  components/domain/AddSurfModal/index.jsx
  constants/apiPath.js
  pages/posts/new/index.jsx
  utils/apis/category/useGetCategories.js
  utils/apis/post/uploadPost.js
  utils/common/shuffle.js
Labels: Wip

#218 Feat: Navbar Link 적용
  components/common/Navbar/index.jsx
Labels: Feat

#209 Feat: post detail 페이지 api 연동
  components/domain/PostDetail/index.jsx
  pages/posts/[month]/[postId]/index.jsx
  utils/apis/follow/deleteFollow.js
  utils/apis/follow/index.js
  utils/apis/follow/postFollow.js
  utils/apis/like/deleteLike.js
  utils/apis/like/index.js
  utils/apis/like/postLike.js
  utils/apis/post/deleteFavorite.js
  utils/apis/post/index.js
  utils/apis/post/postFavorite.js
  utils/apis/post/useGetPost.js
  utils/apis/user/useGetUser.js
Labels: Feat

#222 Refactor: base 컴포넌트 일부 수정
  components/base/Dropdown/index.jsx
  components/base/Input/index.jsx
  components/base/Toggle/index.jsx
Labels: Refactor

#223 Feat: 카테고리 관리 페이지 API 연동
  components/domain/AddSurfModal/index.jsx
  components/domain/AddSurfModal/style.js
  components/domain/CategoryCard/index.jsx
  components/domain/UpdateCategoryModal/index.jsx
  components/domain/index.js
  constants/inputLength.js
  pages/categorymanage/index.jsx
  utils/apis/category/deleteCategory.js
  utils/common/shuffle.js
Labels: Feat

#226 Feat: Dashboard page api 적용
  components/domain/HeatmapChartComponent/index.jsx
  components/domain/RadialBarChartComponent/getFilteredData.js
  components/domain/RadialBarChartComponent/index.jsx
  pages/dashboard/index.jsx
  utils/apis/post/useGetPostsCountYear.js
Labels: Feat

#233 Feat: 둘러보기 페이지 API 1차 연결
  components/domain/Post/index.jsx
  components/domain/Post/style.js
  pages/explore/index.jsx
  pages/posts/new/index.jsx
  utils/apis/follow/index.js
  utils/apis/follow/useGetFollowingPosts.js
  utils/common/timeForToday.js
Labels: Feat

#235 Fix: ellipsis 3줄 말줄임 처리
  components/domain/Post/style.js
Labels: Fix

#237 Feat: 로그인 후 메인페이지로 라우팅
  pages/login/index.jsx
Labels: Feat

#242 Feat: 메인 페이지 api 작업
  components/domain/Post/index.jsx
  pages/index.jsx
  utils/apis/post/index.js
  utils/apis/post/useGetPostsCategory.js
Labels: Feat

#244 Feat: 메인 페이지 1차 완성
  components/domain/Post/index.jsx
  pages/index.jsx
  styles/pageStyles/indexStyle.js
  utils/apis/post/index.js
  utils/apis/post/useGetPostsCategory.js
Labels: Feat

#248 Feat: 둘러보기 페이지 API 연동 및 무한 스크롤 구현
  components/base/Avatar/index.jsx
  components/domain/Post/index.jsx
  components/domain/Post/style.js
  pages/explore/index.jsx
  utils/apis/follow/deleteFollow.js
  utils/apis/post/index.js
  utils/apis/post/useGetRecentPosts.js
  utils/common/timeForToday.js
Labels: Feat

#252 Feat: 일부 페이지별로 뒤로가기 버튼 추가
  components/base/Avatar/index.jsx
  components/domain/PostDetail/index.jsx
  pages/dashboard/index.jsx
  pages/mypage/edit/index.jsx
  pages/posts/[year]/[month]/index.jsx
Labels: Fix, Refactor, Feat

#255 Fix: 배포를 위한 에러 해결
  components/domain/AddSurfModal/index.jsx
  components/domain/AreaChartModule/index.jsx
  components/domain/Carot/index.jsx
  components/domain/UpdateCategoryModal/index.jsx
  pages/404/index.jsx
  pages/404/style.js
  pages/dashboard/index.jsx
  pages/index.jsx
  pages/login/index.jsx
  pages/mypage/[userId]/index.jsx
  pages/mypage/edit/index.jsx
  pages/mypage/index.jsx
  pages/posts/new/index.jsx
  pages/signup/index.jsx
  styles/pageStyles/dashboardStyle.js
  styles/pageStyles/mypageEditStyle.js
  styles/pageStyles/mypageStyle.js
  styles/pageStyles/mypageUserIdStyle.js
  styles/pageStyles/newPostStyle.js
  styles/pageStyles/signUpStyle.js
Labels: Fix

#262 Feat: edit page ui, api 연동
  components/base/MainDropdown/index.jsx
  components/base/Textarea/index.jsx
  components/domain/DatePicker/index.jsx
  components/domain/PostDetail/index.jsx
  components/domain/ScoreSlider/index.jsx
  pages/posts/[year]/[month]/[postId]/edit/index.jsx
  pages/posts/[year]/[month]/[postId]/edit/style.js
  pages/posts/[year]/[month]/[postId]/index.jsx
Labels: Refactor, Feat

#264 Fix: 메인 페이지 일부 수정
  components/domain/index.js
  pages/dashboard/index.jsx
  pages/index.jsx
  utils/apis/post/index.js
  utils/apis/post/useGetPostsCategory.js
Labels: Fix

#266 Feat: logout 기능 추가
  pages/mypage/index.jsx
Labels: Feat

#268 Refactor: Explore 페이지 무한 스크롤 완성
  components/base/Loading/index.jsx
  pages/explore/index.jsx
Labels: Fix, Refactor

#270 Fix: 메인페이지 포스트 분류 오류 수정
  utils/apis/post/useGetPostsCategory.js
Labels: Fix

#273 Feat: Welcome 컴포넌트 구현
  components/base/Logo/index.jsx
  components/domain/Welcome/index.jsx
  components/domain/Welcome/style.js
  components/domain/index.js
  pages/index.jsx
  pages/login/index.jsx
  public/images/logo/index.js
  public/images/logo/logo_italic_white.svg
  stories/domain/Welcome.stories.jsx
Labels: Feat

#274 Feat: 전체 카드 페이지 api 연동
  components/base/MainDropdown/index.jsx
  components/domain/CalendarCard/calendar.jsx
  components/domain/CalendarCard/calendarStyle.js
  components/domain/CalendarCard/index.jsx
  pages/posts/[year]/index.jsx
  utils/apis/post/useGetPostsCountYear.js
Labels: Feat

#276 Fix:attachment추가, postdetail button 관련 lint 오류 해결
  components/domain/PostDetail/index.jsx
  pages/posts/[year]/[month]/[postId]/index.jsx
Labels: Fix

#280 Fix: PostDetail 다른 계정으로 접근시 메뉴 컴포넌트 안보이도록 수정
  components/domain/PostDetail/index.jsx
Labels: Fix

#282 Fix: 메인 페이지 에러 로그 수정
  components/base/Avatar/index.jsx
  components/base/Logo/index.jsx
  components/domain/AreaChartComponent/index.jsx
  pages/index.jsx
Labels: Fix

#285 Refactor: 회원가입 후 welcome 페이지 보여준 후 toast 띄워주기
  pages/index.jsx
  pages/signup/index.jsx
Labels: Refactor

#287 Feat: 카테고리 개수 0일 때 등록 권유 in Main
  components/base/BounceFinger/index.jsx
  components/base/index.js
  pages/index.jsx
  public/images/iconFinger.svg
  stories/base/BounceFinger.stories.jsx
Labels: Feat

#291 Fix: colorCode, profile 수정, avatar preload 설정
  components/base/Avatar/index.jsx
  pages/explore/index.jsx
Labels: Fix

#289 Fix: post detail 메뉴 수정
  components/domain/PostDetail/index.jsx
Labels: Fix

#293 Feat: 스켈레톤 적용, 이미지 preload 설정 in post detail
  components/domain/PostDetail/index.jsx
  pages/posts/[year]/[month]/[postId]/index.jsx
Labels: Feat
